version: '3.8'
services:
  java-app:
    build: .
    container_name: java-17-gc-example-3
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xmx256m -Xmx256m -Xlog:gc*:file=/app/gc/gc.log
    volumes:
      - ./gc:/app/gc/